export const MOVIE_SEARCH_RESULT = 'MOVIE_SEARCH_RESULT'
export const MOVIE_SEARCH_RESULT_ERROR = 'MOVIE_SEARCH_RESULT_ERROR'
export const MOVIE_DETAIL = 'MOVIE_DETAIL'
export const MOVIE_DETAIL_ERROR = 'MOVIE_DETAIL_ERROR'